/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sCal;

import java.awt.event.KeyEvent;

/**
 *
 * @author Anitesh Chowdhury
 */
public class sCal extends javax.swing.JFrame {
    double firstnum;
    double secondnum;
    double result;
    String operations;
    private Object math;
    /**
     * Creates new form sCal
     */
    public sCal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtDisp = new javax.swing.JTextField();
        jBtn8 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtnSubtract = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtndot = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtnSqrt = new javax.swing.JButton();
        jBtnAdd = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();
        jBtnBackspace = new javax.swing.JButton();
        jBtnLog = new javax.swing.JButton();
        jBtnSin = new javax.swing.JButton();
        jBtnSinh = new javax.swing.JButton();
        jBtnpi = new javax.swing.JButton();
        jBtnCos = new javax.swing.JButton();
        jBtnCosh = new javax.swing.JButton();
        jBtnxpowy = new javax.swing.JButton();
        jBtnTan = new javax.swing.JButton();
        jBtnTanh = new javax.swing.JButton();
        jBtnxpow2 = new javax.swing.JButton();
        jBtnCbr = new javax.swing.JButton();
        jBtnRound = new javax.swing.JButton();
        jBtnxpow3 = new javax.swing.JButton();
        jBtnBin = new javax.swing.JButton();
        jBtnHex = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jtxtDisp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtDisp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDispKeyTyped(evt);
            }
        });

        jBtn8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });

        jBtn9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });

        jBtn7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });

        jBtnSubtract.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnSubtract.setText("-");
        jBtnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubtractActionPerformed(evt);
            }
        });

        jBtn5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("*");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jBtn6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });

        jBtn4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });

        jBtn2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setText("/");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jBtn3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });

        jBtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });

        jBtndot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtndot.setText(".");
        jBtndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtndotActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton14.setText("=");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton15.setText("±");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jBtn0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });

        jBtnSqrt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnSqrt.setText("√");
        jBtnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSqrtActionPerformed(evt);
            }
        });

        jBtnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnAdd.setText("+");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jBtnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnClear.setText("C");
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });

        jBtnBackspace.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnBackspace.setText("←");
        jBtnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackspaceActionPerformed(evt);
            }
        });

        jBtnLog.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jBtnLog.setText("Log");
        jBtnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogActionPerformed(evt);
            }
        });

        jBtnSin.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtnSin.setText("Sin");
        jBtnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSinActionPerformed(evt);
            }
        });

        jBtnSinh.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtnSinh.setText("Sinh");
        jBtnSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSinhActionPerformed(evt);
            }
        });

        jBtnpi.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jBtnpi.setText("pi");
        jBtnpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnpiActionPerformed(evt);
            }
        });

        jBtnCos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtnCos.setText("Cos");
        jBtnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCosActionPerformed(evt);
            }
        });

        jBtnCosh.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtnCosh.setText("Cosh");
        jBtnCosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCoshActionPerformed(evt);
            }
        });

        jBtnxpowy.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jBtnxpowy.setText("x^x");
        jBtnxpowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnxpowyActionPerformed(evt);
            }
        });

        jBtnTan.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtnTan.setText("Tan");
        jBtnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTanActionPerformed(evt);
            }
        });

        jBtnTanh.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtnTanh.setText("Tanh");
        jBtnTanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTanhActionPerformed(evt);
            }
        });

        jBtnxpow2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jBtnxpow2.setText("x^2");
        jBtnxpow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnxpow2ActionPerformed(evt);
            }
        });

        jBtnCbr.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtnCbr.setText("Cbr");
        jBtnCbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCbrActionPerformed(evt);
            }
        });

        jBtnRound.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtnRound.setText("Rund");
        jBtnRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRoundActionPerformed(evt);
            }
        });

        jBtnxpow3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jBtnxpow3.setText("x^3");
        jBtnxpow3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnxpow3ActionPerformed(evt);
            }
        });

        jBtnBin.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtnBin.setText("Bin");
        jBtnBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBinActionPerformed(evt);
            }
        });

        jBtnHex.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBtnHex.setText("Hex");
        jBtnHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHexActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Standard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Scientific");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtndot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnSinh))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnpi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCosh))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnxpowy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnTan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnTanh))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnxpow2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCbr, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnRound))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnxpow3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnBin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnHex)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnpi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnxpowy, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnCbr, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnRound, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnxpow2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnBin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnHex, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnxpow3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBtndot, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        // TODO add your handling code here:
        String n=jtxtDisp.getText()+jBtn9.getText();
        jtxtDisp.setText(n);
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
        // TODO add your handling code here:
        String n=jtxtDisp.getText()+jBtn7.getText();
        jtxtDisp.setText(n);
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubtractActionPerformed
        // TODO add your handling code here:
        firstnum =Double.parseDouble(jtxtDisp.getText());
        jtxtDisp.setText(null);
        operations=("-");
    }//GEN-LAST:event_jBtnSubtractActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        firstnum =Double.parseDouble(jtxtDisp.getText());
        jtxtDisp.setText(null);
        operations=("*");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        // TODO add your handling code here:
        String n=jtxtDisp.getText()+jBtn6.getText();
        jtxtDisp.setText(n);
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
        // TODO add your handling code here:
        String n=jtxtDisp.getText()+jBtn4.getText();
        jtxtDisp.setText(n);
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        firstnum =Double.parseDouble(jtxtDisp.getText());
        jtxtDisp.setText(null);
        operations=("/");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        // TODO add your handling code here:
        String n=jtxtDisp.getText()+jBtn3.getText();
        jtxtDisp.setText(n);
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        // TODO add your handling code here:
        String n=jtxtDisp.getText()+jBtn1.getText();
        jtxtDisp.setText(n);
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        String ans;
        secondnum =Double.parseDouble(jtxtDisp.getText());
        if(operations=="+")
        {
            result= firstnum+secondnum;
            ans=String.format("%.2f",result);
            jtxtDisp.setText(ans);
        }
        else if(operations=="-")
        {
            result= firstnum-secondnum;
            ans=String.format("%.2f",result);
            jtxtDisp.setText(ans);
        }
        else if(operations=="*")
        {
            result= firstnum*secondnum;
            ans=String.format("%.2f",result);
            jtxtDisp.setText(ans);
        }
        else if(operations=="/")
        {
            result= firstnum/secondnum;
            ans=String.format("%.2f",result);
            jtxtDisp.setText(ans);
        }
        
        else if(operations=="%")
        {
            result= firstnum%secondnum;
            ans=String.format("%.2f",result);
            jtxtDisp.setText(ans);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        double ops=Double.parseDouble(String.valueOf(jtxtDisp.getText()));
        ops=ops*(-1);
        jtxtDisp.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        // TODO add your handling code here:
        String n=jtxtDisp.getText()+jBtn0.getText();
        jtxtDisp.setText(n);
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setResizable(true);
        this.setSize(250, 380);
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setResizable(true);
        this.setSize(250, 380);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setResizable(true);
        this.setSize(428, 380);
        jtxtDisp.setSize(400, 39);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jBtnSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSqrtActionPerformed
        // TODO add your handling code here:
        double ops=Double.parseDouble(String.valueOf(jtxtDisp.getText()));
        ops=Math.sqrt(ops);
        jtxtDisp.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnSqrtActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        // TODO add your handling code here:
        firstnum =Double.parseDouble(jtxtDisp.getText());
        jtxtDisp.setText(null);
        operations=("+");
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackspaceActionPerformed
        // TODO add your handling code here:
        String bsp=null;
        if(jtxtDisp.getText().length()>0)
        {
            StringBuilder str=new StringBuilder(jtxtDisp.getText());
            str.deleteCharAt(jtxtDisp.getText().length() -1);
            bsp=str.toString();
            jtxtDisp.setText(bsp);
        }
    }//GEN-LAST:event_jBtnBackspaceActionPerformed

    private void jBtnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogActionPerformed
        // TODO add your handling code here:
        double ops=Double.parseDouble(String.valueOf(jtxtDisp.getText()));
        ops=Math.log(ops);
        jtxtDisp.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnLogActionPerformed

    private void jBtnSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSinhActionPerformed
        // TODO add your handling code here:
        double ops=Double.parseDouble(String.valueOf(jtxtDisp.getText()));
        ops=Math.sinh(ops);
        jtxtDisp.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnSinhActionPerformed

    private void jBtnpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnpiActionPerformed
        // TODO add your handling code here:
        double ops;
        ops=(3.1415926535897932384626433832795);
        jtxtDisp.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnpiActionPerformed

    private void jBtnCoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCoshActionPerformed
        // TODO add your handling code here:
        double ops=Double.parseDouble(String.valueOf(jtxtDisp.getText()));
        ops=Math.cosh(ops);
        jtxtDisp.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnCoshActionPerformed

    private void jBtnxpowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnxpowyActionPerformed
        // TODO add your handling code here:
        double ops=Double.parseDouble(String.valueOf(jtxtDisp.getText()));
        ops=Math.pow(ops,ops);
        jtxtDisp.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnxpowyActionPerformed

    private void jBtnTanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTanhActionPerformed
        // TODO add your handling code here:
        double ops=Double.parseDouble(String.valueOf(jtxtDisp.getText()));
        ops=Math.tanh(ops);
        jtxtDisp.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnTanhActionPerformed

    private void jBtnxpow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnxpow2ActionPerformed
        // TODO add your handling code here:
        double ops=Double.parseDouble(String.valueOf(jtxtDisp.getText()));
        ops=ops*ops;
        jtxtDisp.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnxpow2ActionPerformed

    private void jBtnRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRoundActionPerformed
        double ops=Double.parseDouble(String.valueOf(jtxtDisp.getText()));
        ops=Math.round(ops);
        jtxtDisp.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnRoundActionPerformed

    private void jBtnxpow3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnxpow3ActionPerformed
        // TODO add your handling code here:
        double ops=Double.parseDouble(String.valueOf(jtxtDisp.getText()));
        ops=(ops*ops*ops);
        jtxtDisp.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnxpow3ActionPerformed

    private void jBtnHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHexActionPerformed
        // TODO add your handling code here:
        int a =Integer.parseInt(jtxtDisp.getText());
        jtxtDisp.setText(Integer.toString(a, 16));
    }//GEN-LAST:event_jBtnHexActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
        // TODO add your handling code here:
        String n=jtxtDisp.getText()+jBtn8.getText();
        jtxtDisp.setText(n);
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        // TODO add your handling code here:
        String n=jtxtDisp.getText()+jBtn5.getText();
        jtxtDisp.setText(n);
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        // TODO add your handling code here:
        String n=jtxtDisp.getText()+jBtn2.getText();
        jtxtDisp.setText(n);
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        // TODO add your handling code here:
        jtxtDisp.setText("");
    }//GEN-LAST:event_jBtnClearActionPerformed

    private void jBtndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtndotActionPerformed
        // TODO add your handling code here:
        if(!jtxtDisp.getText().contains("."))
        {
            jtxtDisp.setText(jtxtDisp.getText()+jBtndot.getText());
        }
    }//GEN-LAST:event_jBtndotActionPerformed

    private void jBtnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSinActionPerformed
        // TODO add your handling code here:
        double ops=Double.parseDouble(String.valueOf(jtxtDisp.getText()));
        ops=Math.sin(ops);
        jtxtDisp.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnSinActionPerformed

    private void jBtnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCosActionPerformed
        // TODO add your handling code here:
        double ops=Double.parseDouble(String.valueOf(jtxtDisp.getText()));
        ops=Math.cos(ops);
        jtxtDisp.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnCosActionPerformed

    private void jBtnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTanActionPerformed
        // TODO add your handling code here:
        double ops=Double.parseDouble(String.valueOf(jtxtDisp.getText()));
        ops=Math.tan(ops);
        jtxtDisp.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnTanActionPerformed

    private void jBtnCbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCbrActionPerformed
        // TODO add your handling code here:
        double ops=Double.parseDouble(String.valueOf(jtxtDisp.getText()));
        ops=Math.cbrt(ops);
        jtxtDisp.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnCbrActionPerformed

    private void jBtnBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBinActionPerformed
        // TODO add your handling code here:
        int a =Integer.parseInt(jtxtDisp.getText());
        jtxtDisp.setText(Integer.toString(a, 2));
    }//GEN-LAST:event_jBtnBinActionPerformed

    private void jtxtDispKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDispKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
           evt.consume();
        }
    }//GEN-LAST:event_jtxtDispKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sCal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnBackspace;
    private javax.swing.JButton jBtnBin;
    private javax.swing.JButton jBtnCbr;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnCos;
    private javax.swing.JButton jBtnCosh;
    private javax.swing.JButton jBtnHex;
    private javax.swing.JButton jBtnLog;
    private javax.swing.JButton jBtnRound;
    private javax.swing.JButton jBtnSin;
    private javax.swing.JButton jBtnSinh;
    private javax.swing.JButton jBtnSqrt;
    private javax.swing.JButton jBtnSubtract;
    private javax.swing.JButton jBtnTan;
    private javax.swing.JButton jBtnTanh;
    private javax.swing.JButton jBtndot;
    private javax.swing.JButton jBtnpi;
    private javax.swing.JButton jBtnxpow2;
    private javax.swing.JButton jBtnxpow3;
    private javax.swing.JButton jBtnxpowy;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jtxtDisp;
    // End of variables declaration//GEN-END:variables
}
